export const cards = [
  {
    imgSrc: "/src/assets/solutions1.png",
    altText: "INS Jyoti",
    title: "INS Jyoti",
    desc: "Komandarm Fedko class fleet replenishment oiler",
    bgColor: "bg-background",
    textColor: "text-primary",
    descColor: "text-white",
  },
  {
    imgSrc: "/src/assets/solutions2.png",
    altText: "INS Beas",
    title: "INS Beas",
    desc: "Bhahmaputra class frigate",
    bgColor: "bg-white",
    textColor: "text-secondary",
    descColor: "text-background",
  },
  {
    imgSrc: "/src/assets/solutions3.png",
    altText: "INS Nireekshak",
    title: "INS Nireekshak",
    desc: "Diving support vessel",
    bgColor: "bg-background",
    textColor: "text-primary",
    descColor: "text-white",
  },
  {
    imgSrc: "/src/assets/solutions4.png",
    altText: "MT Swarna Kalash",
    title: "MT Swarna Kalash",
    desc: "Oil products tanker",
    bgColor: "bg-white",
    textColor: "text-secondary",
    descColor: "text-background",
  },
  {
    imgSrc: "/src/assets/solutions5.png",
    altText: "INS Tarangini and INS Sudarshini",
    title: "INS Tarangini and INS Sudarshini",
    desc: "Sail training ship",
    bgColor: "bg-background",
    textColor: "text-primary",
    descColor: "text-white",
  },
  {
    imgSrc: "/src/assets/solutions6.png",
    altText: "MV Arabian Sea",
    title: "MV Arabian Sea",
    desc: "General passenger/cargo ship",
    bgColor: "bg-white",
    textColor: "text-secondary",
    descColor: "text-background",
  },
];
